name: Deploy to github pagesc

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install deps
        run: |
          npm -g install pnpm
          pnpm install --frozen-lockfile
      - name: Build
        run: pnpm build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build.art
          path: ./dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build.art
          path: ./_static
      - run: mv ./_static/index.html index.html
      - run: ls -l
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .

